[project]
name = "mcp-server-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastmcp>=2.12.4",
    "langchain-groq>=0.3.8",
    "mcp-use>=1.3.12",
]
